version: '3.5'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: brands
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
